data:
  data_root: "/cluster/project/cvg/data/EgoExo_georgiatech/raw/takes"
  output_directory: "/cluster/project/cvg/students/tnanni/ghost/test_outputs/new_new_segmentation_test_15"
  slice: 1                    # Number of scenes to load (set for testing)
  exclude_egocentric: true    # Exclude egocentric videos for simplicity
  smplx_model_path: "body_models"
  mhr_model_path: null

segmentation:
  checkpoint_path: null         # Path to SAM3 checkpoint; null = auto-download from HuggingFace
  text_prompt: "person"         # Text query for SAM3 detection
  redetect_interval: 15         # Add text prompt every N frames so late arrivals are detected

parameters_extraction:
  reid_threshold: 0.75
  gallery_moving_average_alpha: 0.9
  sam3d_id: "facebook/sam-3d-body-dinov3"
  sam3d_step: 1               # Predict using sam3d every sam3d_step frames
  bbox_padding: 0.2           # Padding added to the bounding box before cropping the image for SAM3D.    
